exports.ERROR_MONGOOSE_VALIDATE = "ERROR_MONGOOSE_VALIDATE";
exports.ERROR_VALIDATE = "ERROR_VALIDATE";
exports.ERROR_EMAIL_NOT_EXISTS = "ERROR_EMAIL_NOT_EXISTS";
exports.ERROR_PASSWORD_NOT_MATCH = "ERROR_PASSWORD_NOT_MATCH";
exports.ERROR_TOKEN_INVALID = "ERROR_TOKEN_INVALID";
exports.NOT_FOUND= "NOT_FOUND"